#!/usr/bin/env python
import os
import sys
import pyglet

try:
    from useboxnet.puzzle import Main
except ImportError:
    # make things easier to run without installing
    path = os.path.dirname(os.path.abspath(__file__))
    if "scripts" in path:
        sys.path.append(os.path.join(path, '..'))
    else:
        sys.path.append(path)
    from useboxnet.puzzle import Main

if __name__ == "__main__":
    main = Main()
    pyglet.app.run()

